# proof-of-passport-config.toml

[build]
# For iOS device_type can be x86_64, simulator, device
# For Android device_type can be x86_64, arm, arm64
device_type = "device" # Options: x86_64, simulator, device, arm, arm64

# debug is for Rust library to be in debug mode and release for release mode
# We recommend release mode by default for performance
build_mode = "release" # Options: debug, release

[circuit]
dir = "examples/circom/proof_of_passport" # Directory of the circuit
name = "proof_of_passport"       # Name of the circuit

[dylib]
# NOTE: Dylib support is experimental and requires some fiddling in iOS
# See https://github.com/oskarth/mopro/pull/37 and https://github.com/oskarth/mopro/pull/38
use_dylib = false        # Options: true, false
name = "proof_of_passport.dylib" # Name of the dylib file, only used if use_dylib is true
